name: build-master

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]
  workflow_dispatch:

jobs:
  build:
    permissions: write-all
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      
      - uses: actions/setup-node@v3
        with:
          node-version: 16
          
      - run: npm install --save @flybywiresim/fragmenter

      - run: mkdir scenery/ContentInfo/${{ github.event.repository.name }}

      - run: cp resource/Thumbnail.jpg scenery/ContentInfo/${{ github.event.repository.name }}/

      - run: node script/index.js

      - run: git tag -d production || true

      - run: git push origin :production || true

      - run: sleep 3

      - name: Create Release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} # This token is provided by Actions, you do not need to create your own token
        with:
          tag_name: production
          release_name: Release production
          draft: false
          prerelease: false

      - name: upload modules.json
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} # This token is provided by Actions, you do not need to create your own token
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: build-modules/modules.json
          asset_name: modules.json
          asset_content_type: application/json

      - name: upload base.zip
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} # This token is provided by Actions, you do not need to create your own token
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: build-modules/base.zip
          asset_name: base.zip
          asset_content_type: application/zip

      - name: upload full.zip
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} # This token is provided by Actions, you do not need to create your own token
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: build-modules/full.zip
          asset_name: full.zip
          asset_content_type: application/zip
